# Generated by Django 3.0.1 on 2019-12-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("key", models.CharField(max_length=3)),
                ("sheet_type", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Setlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("worship_leader", models.CharField(max_length=30)),
                ("songs", models.ManyToManyField(to="songbook.Song")),
            ],
        ),
    ]
