# Generated by Django 3.0.1 on 2020-01-31 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('songbook', '0002_auto_20200108_1338'), ('songbook', '0003_auto_20200130_0948'), ('songbook', '0004_auto_20200130_1001'), ('songbook', '0005_auto_20200130_1005'), ('songbook', '0006_auto_20200130_1016'), ('songbook', '0007_auto_20200130_1024'), ('songbook', '0008_team_positions'), ('songbook', '0009_auto_20200130_1211'), ('songbook', '0010_auto_20200130_1239'), ('songbook', '0011_arrangement_key'), ('songbook', '0012_auto_20200130_1744'), ('songbook', '0013_auto_20200130_1804'), ('songbook', '0014_auto_20200131_0708'), ('songbook', '0015_auto_20200131_1130'), ('songbook', '0016_plan_service_type')]

    dependencies = [
        ('songbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='sheet_type',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'key')},
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('people', models.ManyToManyField(blank=True, related_name='positions', to='songbook.Person')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='songbook.Team')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.RenameField(
            model_name='song',
            old_name='key',
            new_name='original_key',
        ),
        migrations.AlterField(
            model_name='song',
            name='original_key',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='sheet_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recurrence', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songbook.Person')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songbook.Position')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('stopping_time', models.TimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_times', to='songbook.ServiceType')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='songbook.ServiceType'),
        ),
        migrations.CreateModel(
            name='SongArrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Arrangement', max_length=100)),
                ('length', models.CharField(blank=True, max_length=20, null=True)),
                ('bpm', models.IntegerField(blank=True, null=True, verbose_name='BPM')),
                ('meter', models.CharField(blank=True, max_length=20, null=True)),
                ('sequence', models.CharField(blank=True, max_length=255, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='songbook.Song')),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'original_key')},
        ),
        migrations.CreateModel(
            name='TeamArrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_arrangements', models.ManyToManyField(related_name='team_arrangements', to='songbook.PositionAssignment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songbook.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='sheet_type',
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('song_arrangements', models.ManyToManyField(related_name='plans', to='songbook.Arrangement')),
                ('team_arrangement', models.ManyToManyField(related_name='plans', to='songbook.PersonSchedule')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songbook.ServiceType')),
            ],
        ),
    ]
