# Generated by Django 3.0.1 on 2020-01-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songbook", "0002_auto_20200108_1338"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50, null=True)),
                (
                    "nick_name",
                    models.CharField(
                        default=models.CharField(max_length=50),
                        max_length=50,
                        null=True,
                    ),
                ),
                ("gender", models.CharField(max_length=10, null=True)),
                ("birthday", models.DateField(null=True)),
                ("phone_number", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="song", name="name", field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(name="song", unique_together={("name", "key")},),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("people", models.ManyToManyField(to="songbook.Person")),
            ],
        ),
        migrations.CreateModel(
            name="Instrumentation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="songbook.Instrument",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="songbook.Person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="setlist",
            name="instrumentation",
            field=models.ManyToManyField(to="songbook.Instrumentation"),
        ),
    ]
