# Generated by Django 3.0.1 on 2020-01-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songbook", "0003_auto_20200130_0948"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": "Position", "verbose_name_plural": "Positions"},
        ),
    ]
