# Generated by Django 3.0.1 on 2020-01-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songbook", "0004_auto_20200130_1001"),
    ]

    operations = [
        migrations.AlterModelOptions(name="position", options={},),
        migrations.AlterField(
            model_name="position",
            name="people",
            field=models.ManyToManyField(
                related_name="positions", to="songbook.Person"
            ),
        ),
    ]
