# Generated by Django 3.0.1 on 2020-01-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songbook", "0006_auto_20200130_1016"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person", old_name="nick_name", new_name="_nickname",
        ),
        migrations.RemoveField(model_name="person", name="localization",),
    ]
