# Generated by Django 3.0.1 on 2020-01-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songbook", "0007_auto_20200130_1024"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="positions",
            field=models.ManyToManyField(related_name="teams", to="songbook.Position"),
        ),
    ]
