# Generated by Django 3.0.1 on 2020-01-30 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songbook", "0009_auto_20200130_1211"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arrangement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("length", models.CharField(blank=True, max_length=20, null=True)),
                ("bpm", models.IntegerField(blank=True, null=True, verbose_name="BPM")),
                ("meter", models.CharField(blank=True, max_length=20, null=True)),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "arrangements",
                    models.ManyToManyField(
                        related_name="plans", to="songbook.Arrangement"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="instrumentation", name="instrument",),
        migrations.RemoveField(model_name="instrumentation", name="player",),
        migrations.RemoveField(model_name="setlist", name="instrumentation",),
        migrations.RemoveField(model_name="team", name="positions",),
        migrations.AddField(
            model_name="position",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="songbook.Team",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="key",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="sheet_type",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.DeleteModel(name="Instrument",),
        migrations.DeleteModel(name="Instrumentation",),
        migrations.AddField(
            model_name="arrangement",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrangements",
                to="songbook.Song",
            ),
        ),
    ]
