# Generated by Django 3.0.1 on 2020-01-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songbook", "0012_auto_20200130_1744"),
    ]

    operations = [
        migrations.RenameModel(old_name="PersonSchedule", new_name="TeamArrangement",),
    ]
