# Generated by Django 3.0.1 on 2020-01-31 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songbook", "0013_auto_20200130_1804"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("recurrence", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="TeamArrangement", new_name="PositionAssignment",
        ),
        migrations.RenameModel(old_name="Arrangement", new_name="SongArrangement",),
        migrations.RenameField(
            model_name="plan", old_name="arrangements", new_name="song_arrangements",
        ),
        migrations.RenameField(
            model_name="plan", old_name="people", new_name="team_arrangement",
        ),
        migrations.CreateModel(
            name="ServiceTime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("starting_time", models.TimeField()),
                ("stopping_time", models.TimeField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_times",
                        to="songbook.ServiceType",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="songbook.ServiceType",
            ),
        ),
    ]
