# Generated by Django 3.0.1 on 2020-01-31 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songbook", "0014_auto_20200131_0708"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song", old_name="key", new_name="original_key",
        ),
        migrations.AlterField(
            model_name="songarrangement",
            name="key",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="song", unique_together={("name", "original_key")},
        ),
        migrations.CreateModel(
            name="TeamArrangement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_arrangements",
                    models.ManyToManyField(
                        related_name="team_arrangements",
                        to="songbook.PositionAssignment",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="songbook.Team"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="song", name="sheet_type",),
    ]
