# Generated by Django 3.0.1 on 2020-01-31 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0015_auto_20200131_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songbook.ServiceType'),
        ),
    ]
