# Generated by Django 3.0.1 on 2020-01-31 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("nickname", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "people",
                    models.ManyToManyField(
                        blank=True, related_name="positions", to="songbook.Person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PositionAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="confirmed", max_length=20)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="songbook.Person",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="songbook.Position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("recurrence", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("original_key", models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={"unique_together": {("name", "original_key")},},
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "service_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="songbook.ServiceType",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamArrangement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_assignments",
                    models.ManyToManyField(
                        related_name="team_arrangements",
                        to="songbook.PositionAssignment",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="songbook.Team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongArrangement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Default Arrangement", max_length=100),
                ),
                ("key", models.CharField(blank=True, max_length=10, null=True)),
                ("length", models.CharField(blank=True, max_length=20, null=True)),
                ("bpm", models.IntegerField(blank=True, null=True, verbose_name="BPM")),
                ("meter", models.CharField(blank=True, max_length=20, null=True)),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_arrangements",
                        to="songbook.Song",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Setlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("worship_leader", models.CharField(max_length=30)),
                ("songs", models.ManyToManyField(to="songbook.Song")),
            ],
        ),
        migrations.CreateModel(
            name="ServiceTime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("starting_time", models.TimeField()),
                ("stopping_time", models.TimeField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_times",
                        to="songbook.ServiceType",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="position",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="songbook.Team",
            ),
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "service_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="songbook.ServiceType",
                    ),
                ),
                (
                    "song_arrangements",
                    models.ManyToManyField(
                        related_name="plans", to="songbook.SongArrangement"
                    ),
                ),
                (
                    "team_arrangement",
                    models.ManyToManyField(
                        related_name="plans", to="songbook.TeamArrangement"
                    ),
                ),
            ],
        ),
    ]
