# Generated by Django 3.0.3 on 2020-02-07 01:09

import datetime

import django.db.models.deletion
import songbook.models
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("songbook", "0005_remove_song_arrangement_table"),
    ]

    operations = [
        migrations.RenameField(model_name="song", old_name="name", new_name="title",),
        migrations.AddField(
            model_name="plan",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SongAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("audio", "Audio File"), ("sheet", "Music Sheet")],
                        max_length=64,
                    ),
                ),
                (
                    "main",
                    models.BooleanField(
                        default=True,
                        help_text="Whether or not that this attachment should be listed as the mainattachment on a song list view.",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(upload_to=songbook.models.song_attachment_path),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            2020, 2, 7, 1, 9, 5, 529065, tzinfo=utc
                        ),
                        null=True,
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="songbook.Song",
                    ),
                ),
            ],
        ),
    ]
