# Generated by Django 3.0.3 on 2020-02-07 01:16

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("songbook", "0006_auto_20200207_0909"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songattachment",
            name="created",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2020, 2, 7, 1, 16, 4, 125850, tzinfo=utc),
                null=True,
            ),
        ),
    ]
