name: Test and Deploy
on:
  push:
    branches: 
      - master
      - develop
      - feature/test-on-develop

jobs:
  test:
    name: Test and Deploy
    runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
          source $HOME/.poetry/env

      - name: Install dependencies
        run: poetry install -v

      - name: Lint
        run: poetry run tox -e lint

      - name: Test
        run: poetry run tox -e py36
          
      - name: Deploy
        if: github.ref == 'master'
        env:
          LW_HOST: ${{ secrets.LWHost }}
          LW_USER: ${{ secrets.LWUser }}
          LW_PASSWORD: ${{ secrets.LWPassword }}
          LW_PORT: ${{ secrets.LWPort }}
        run: |
          source $HOME/.poetry/env
          poetry run fab deploy
